/**
  public OnPlayerConnect(playerid)
  {
    if (player.connect(playerid)) {
        printf "%d %s", playerid, "Is Connected!";
    }
    return 1;
  }
 **/
#define player. player_
#define player_connect      IsPlayerConnected
#define player_ammo         GetPlayerAmmo
#define player_health       GetPlayerHealth
#define player_armour       GetPlayerArmour
#define player_team         GetPlayerTeam
#define player_score        GetPlayerScore
#define player_drunk        GetPlayerDrunkLevel

#define weapon. weapon_
#define weapon_state        GetPlayerWeaponState
#define weapon_data         GetPlayerWeaponData
