#define player. player_
#define player_connect          IsPlayerConnected
#define player_ammo             GetPlayerAmmo
#define player_health           GetPlayerHealth
#define player_armour           GetPlayerArmour
#define player_team             GetPlayerTeam
#define player_score            GetPlayerScore
#define player_drunk            GetPlayerDrunkLevel
#define player_name             GetPlayername
#define player_money            GetPlayerMoney
#define player_interior         GetPlayerInterior
#define player_world            GetPlayerVirtualWorld

#define control. control_
#define control_special_action  GetPlayerSpecialAction
#define control_animation       GetAnimationName
#define control_animdex         GetPlayerAnimationIndex

#define camera. camera_
#define camera_zoom             GetPlayerCameraZoom
#define camera_asrat            GetPlayerCameraAspectRatio
#define camera_mode             GetPlayerCameraMode
#define camera_pos              GetPlayerCameraPos
#define camera_front_vector     GetPlayerCameraFrontVector
#define camera_target_actor     GetPlayerCameraTargetActor
#define camera_target_player    GetPlayerCameraTargetPlayer
#define camera_target_vehicle   GetPlayerCameraTargetVehicle
#define camera_target_object    GetPlayerCameraTargetObject

#define weapon. weapon_
#define weapon_state            GetPlayerWeaponState
#define weapon_data             GetPlayerWeaponData
